version: "2"
services:
  injector:
    build: injector
    depends_on:
      - controller
    deploy:
      replicas: 10
    volumes:
      - ./injector/results:/injector/results
  controller:
    build: controller
    ports:
    - "8000:80"
