FROM accelsim/ubuntu-18.04_cuda-11:latest
RUN rm /bin/sh && ln -s /bin/bash /bin/sh
RUN echo 'PATH=$PATH:/usr/local/cuda/bin' > ~/.bashrc
RUN echo 'CUDA_INSTALL_PATH=/usr/local/cuda-11.0' > ~/.bashrc
RUN echo 'LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH' > ~/.bashrc
RUN source ~/.bashrc
WORKDIR /injector
COPY . .
RUN chmod +x init
RUN ./init
WORKDIR /injector/python
EXPOSE 5000
RUN python3.8 -m pip install -r requeriments.txt
ENTRYPOINT [ "python3.8" ]
CMD [ "app.py" ]
