FROM accelsim/ubuntu-18.04_cuda-11:latest
RUN rm /bin/sh && ln -s /bin/bash /bin/sh
WORKDIR /injector
COPY . .
RUN chmod +x init
RUN ./init
WORKDIR /injector/python
EXPOSE 5000
RUN python3.8 -m pip install -r requeriments.txt
ENTRYPOINT [ "python3.8" ]
CMD [ "app.py" ]
