#!/bin/bash
#
# Robert Alexander Limas Sierra
#
APP_DIR=`pwd`
apt install python3.8 -y

export CUDA_INSTALL_PATH=/usr/local/cuda-11.0
export PATH=$PATH:/usr/local/cuda/bin
export CUDA_INSTALL_PATH=/usr/local/cuda-11.0
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH

git clone https://github.com/gpgpu-sim/gpgpu-sim_distribution.git

cd ${APP_DIR}/gpgpu-sim_distribution
source setup_environment
make
