#!/bin/bash
#
# Robert Alexander Limas Sierra
#
APP_DIR=`pwd`
apt install python3.8 -y

export PATH=$PATH:/usr/local/cuda/bin
export CUDA_INSTALL_PATH=/usr/local/cuda
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH

git clone https://github.com/gpgpu-sim/gpgpu-sim_distribution.git

cd ${APP_DIR}/gpgpu-sim_distribution
make clean
source setup_environment
make

cd ${APP_DIR}/apps

git clone https://github.com/robalexlimas/rodinia.git
cd ${APP_DIR}/apps/rodinia
git checkout rodinia_gpgpusim
git pull
chmod +x -R .
make clean
make
