#!/bin/bash
#
# Robert Alexander Limas Sierra
#
APP_DIR=`pwd`
apt-get install python3.7 curl -y
apt-get install curl -y
python3 ${APP_DIR}/get-pip.py --user

export CUDA_INSTALL_PATH=/usr/local/cuda-11.0
export PATH=$PATH:/usr/local/cuda/bin
export CUDA_INSTALL_PATH=/usr/local/cuda-11.0
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH

git clone https://github.com/gpgpu-sim/gpgpu-sim_distribution.git

cd ${APP_DIR}/gpgpu-sim_distribution
source setup_environment
make
